# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 20, 0, 19, 185599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 20, 0, 19, 184573, tzinfo=utc)),
        ),
    ]
